alter table FACILITYMANAGEMENT_ALLEGATION add column QUALIFIER2_ID integer ;
alter table FACILITYMANAGEMENT_ALLEGATION add column QUALIFIER1_ID integer ;
alter table FACILITYMANAGEMENT_ALLEGATION add column BODILY_INJURY_ID integer ;
alter table FACILITYMANAGEMENT_ALLEGATION add column OPEN_HAND_OR_CLOSED_FIST varchar(255) ;
alter table FACILITYMANAGEMENT_ALLEGATION add column SHAPE_MARK_OF_INJURY varchar(255) ;
alter table FACILITYMANAGEMENT_ALLEGATION add column RECURRING_EVENT varchar(255) ;
