alter table FACILITYMANAGEMENT_COMPLAINT add column DID_INCIDENT_TAKE_PLACE_IN_FACILITY_ID integer ;
alter table FACILITYMANAGEMENT_COMPLAINT add column WHAT_HAPPENED longvarchar ;
alter table FACILITYMANAGEMENT_COMPLAINT add column OTHER_DETAILS_OF_LOCATION varchar(1000) ;
