alter table FACILITYMANAGEMENT_COMPLAINT alter column CONTROL_NUMBER rename to CONTROL_NUMBER__U52446 ^
alter table FACILITYMANAGEMENT_COMPLAINT alter column PHONE_NUMBER rename to PHONE_NUMBER__U41423 ^
alter table FACILITYMANAGEMENT_COMPLAINT alter column STATE_ID rename to STATE_ID__U96475 ^
alter table FACILITYMANAGEMENT_COMPLAINT drop constraint FK_FACILITYMANAGEMENT_COMPLAINT_ON_STATE ;
drop index IDX_FACILITYMANAGEMENT_COMPLAINT_ON_STATE ;
alter table FACILITYMANAGEMENT_COMPLAINT alter column ZIP rename to ZIP__U77672 ^
alter table FACILITYMANAGEMENT_COMPLAINT alter column CITY rename to CITY__U55637 ^
alter table FACILITYMANAGEMENT_COMPLAINT alter column ADDRESS_LINE2 rename to ADDRESS_LINE2__U10107 ^
alter table FACILITYMANAGEMENT_COMPLAINT alter column ADDRESS_LINE1 rename to ADDRESS_LINE1__U30458 ^
alter table FACILITYMANAGEMENT_COMPLAINT alter column TYPE_OF_FACILITY_ID rename to TYPE_OF_FACILITY_ID__U59239 ^
alter table FACILITYMANAGEMENT_COMPLAINT drop constraint FK_FACILITYMANAGEMENT_COMPLAINT_ON_TYPE_OF_FACILITY ;
drop index IDX_FACILITYMANAGEMENT_COMPLAINT_ON_TYPE_OF_FACILITY ;
alter table FACILITYMANAGEMENT_COMPLAINT alter column FACILITY_FILE_NUMBER rename to FACILITY_FILE_NUMBER__U18596 ^
